# Generated by Django 4.2.10 on 2024-03-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='username',
        ),
    ]
